import type { Metadata } from "next";
import { Inter_Tight, Lexend } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Hydrate from "../lib/hydrate-client";
import "./globals.css";
import Providers from "./providers";
import { ThemeProvider } from "./theme-provider";

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const interTight = Inter_Tight({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

console.log(lexend, "inter");

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <body className={lexend.className}>
          <Toaster position="top-right" />
          <Providers>
            <Hydrate>{children}</Hydrate>
          </Providers>
        </body>
      </ThemeProvider>
    </html>
  );
}
